config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  # def new
  # end

  # def create
  # end

  # def update
  # end

  # def edit
  # end

  # def show
  # end

  # def destroy
  # end

  # def index
  # end


  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])

  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    # @Flat.save # Will raise ActiveModel::ForbiddenAttributesError
    if @flat.save
      redirect_to @flat
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])

    if @flat.update(flat_params)
      redirect_to @flat
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy

    redirect_to flat_path, status: :see_other
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/create.html.erb
<h1>Flats#create</h1>
<p>Find me in app/views/flats/create.html.erb</p>

app/views/flats/destroy.html.erb
<h1>Flats#destroy</h1>
<p>Find me in app/views/flats/destroy.html.erb</p>

app/views/flats/edit.html.erb
<h1>Flats#edit</h1>
<p>Find me in app/views/flats/edit.html.erb</p>

app/views/flats/index.html.erb
<div class="container w-100">
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <form class="container-fluid justify-content-start">
        <button class="btn btn-outline-success me-2" type="button">Add Flat</button>

      </form>
    </div>

  </nav>


  <h1>All our flat</h1>
  <p>all our <%= @flats.count %> flats</p>
  <div class="d-flex">

    <% @flats.each do |flat| %>
    <div class="card " style="width: 18rem;">
      <img class="card-img-top" src="..." alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title"><%= flat.name %></h5>
        <p class="card-text"><%= flat.description %></p>
        <%= link_to "details", flat_path(flat)  %> <%= link_to "edit", edit_flat_path(flat)  %> <%= link_to "delete", flat_path(flat), data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        }  %>




      </div>

    </div>
    <% end  %>




  </div>
</div>

app/views/flats/new.html.erb
<h1>Flats#new</h1>
<p>Find me in app/views/flats/new.html.erb</p>

app/views/flats/show.html.erb
<h1>Flats#show</h1>
<p>Find me in app/views/flats/show.html.erb</p>

app/views/flats/update.html.erb
<h1>Flats#update</h1>
<p>Find me in app/views/flats/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>RailsSimpleAirbnb</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <%= yield %>
</body>

</html>